package LolChatRiotDb;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import LolChatRiotDb.MessageDb;

import LolChatRiotDb.MessageDbDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig messageDbDaoConfig;

    private final MessageDbDao messageDbDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        messageDbDaoConfig = daoConfigMap.get(MessageDbDao.class).clone();
        messageDbDaoConfig.initIdentityScope(type);

        messageDbDao = new MessageDbDao(messageDbDaoConfig, this);

        registerDao(MessageDb.class, messageDbDao);
    }
    
    public void clear() {
        messageDbDaoConfig.getIdentityScope().clear();
    }

    public MessageDbDao getMessageDbDao() {
        return messageDbDao;
    }

}
