package LolChatRiotDb;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MESSAGE_DB.
 */
public class MessageDb {

    private Long id;
    private String message_riotXmppUser;
    private Integer message_from_or_to;
    private java.util.Date message_date;
    private String message_message;

    public MessageDb() {
    }

    public MessageDb(Long id) {
        this.id = id;
    }

    public MessageDb(Long id, String message_riotXmppUser, Integer message_from_or_to, java.util.Date message_date, String message_message) {
        this.id = id;
        this.message_riotXmppUser = message_riotXmppUser;
        this.message_from_or_to = message_from_or_to;
        this.message_date = message_date;
        this.message_message = message_message;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMessage_riotXmppUser() {
        return message_riotXmppUser;
    }

    public void setMessage_riotXmppUser(String message_riotXmppUser) {
        this.message_riotXmppUser = message_riotXmppUser;
    }

    public Integer getMessage_from_or_to() {
        return message_from_or_to;
    }

    public void setMessage_from_or_to(Integer message_from_or_to) {
        this.message_from_or_to = message_from_or_to;
    }

    public java.util.Date getMessage_date() {
        return message_date;
    }

    public void setMessage_date(java.util.Date message_date) {
        this.message_date = message_date;
    }

    public String getMessage_message() {
        return message_message;
    }

    public void setMessage_message(String message_message) {
        this.message_message = message_message;
    }

}
