package LolChatRiotDb;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MESSAGE_DB.
 */
public class MessageDb {

    private Long id;
    private String userXmppId;
    private String fromTo;
    private Integer direction;
    private java.util.Date date;
    private String message;
    private Boolean wasRead;

    public MessageDb() {
    }

    public MessageDb(Long id) {
        this.id = id;
    }

    public MessageDb(Long id, String userXmppId, String fromTo, Integer direction, java.util.Date date, String message, Boolean wasRead) {
        this.id = id;
        this.userXmppId = userXmppId;
        this.fromTo = fromTo;
        this.direction = direction;
        this.date = date;
        this.message = message;
        this.wasRead = wasRead;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserXmppId() {
        return userXmppId;
    }

    public void setUserXmppId(String userXmppId) {
        this.userXmppId = userXmppId;
    }

    public String getFromTo() {
        return fromTo;
    }

    public void setFromTo(String fromTo) {
        this.fromTo = fromTo;
    }

    public Integer getDirection() {
        return direction;
    }

    public void setDirection(Integer direction) {
        this.direction = direction;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public Boolean getWasRead() {
        return wasRead;
    }

    public void setWasRead(Boolean wasRead) {
        this.wasRead = wasRead;
    }

    @Override
    public String toString() {
        return "MessageDb{" +
                "id=" + id +
                ", userXmppId='" + userXmppId + '\'' +
                ", fromTo='" + fromTo + '\'' +
                ", direction=" + direction +
                ", date=" + date +
                ", message='" + message + '\'' +
                ", wasRead=" + wasRead +
                '}';
    }
}
