package LolChatRiotDb;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table NOTIFICATION_DB.
 */
public class NotificationDb {

    private Long id;
    private String userXmppId;
    private Boolean soundNotificationOnline;
    private Boolean soundNotificationOffline;
    private Boolean textNotificationOnline;
    private Boolean textNotificationOffline;

    public NotificationDb() {
    }

    public NotificationDb(Long id) {
        this.id = id;
    }

    /**
     *
     * @param id
     * @param userXmppId: eg; sum12345@pvp.net
     * @param soundNotificationOnline
     * @param soundNotificationOffline
     * @param textNotificationOnline
     * @param textNotificationOffline
     */
    public NotificationDb(Long id, String userXmppId, Boolean soundNotificationOnline, Boolean soundNotificationOffline, Boolean textNotificationOnline, Boolean textNotificationOffline) {
        this.id = id;
        this.userXmppId = userXmppId;
        this.soundNotificationOnline = soundNotificationOnline;
        this.soundNotificationOffline = soundNotificationOffline;
        this.textNotificationOnline = textNotificationOnline;
        this.textNotificationOffline = textNotificationOffline;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserXmppId() {
        return userXmppId;
    }

    public void setUserXmppId(String userXmppId) {
        this.userXmppId = userXmppId;
    }

    public Boolean getSoundNotificationOnline() {
        return soundNotificationOnline;
    }

    public void setSoundNotificationOnline(Boolean soundNotificationOnline) {
        this.soundNotificationOnline = soundNotificationOnline;
    }

    public Boolean getSoundNotificationOffline() {
        return soundNotificationOffline;
    }

    public void setSoundNotificationOffline(Boolean soundNotificationOffline) {
        this.soundNotificationOffline = soundNotificationOffline;
    }

    public Boolean getTextNotificationOnline() {
        return textNotificationOnline;
    }

    public void setTextNotificationOnline(Boolean textNotificationOnline) {
        this.textNotificationOnline = textNotificationOnline;
    }

    public Boolean getTextNotificationOffline() {
        return textNotificationOffline;
    }

    public void setTextNotificationOffline(Boolean textNotificationOffline) {
        this.textNotificationOffline = textNotificationOffline;
    }

}
